pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./administraton_guide.html","Rus &#62; Руководство администратора","Данное руководство содержит набор статей, описывающих как настроить и использовать TrackStudio для управления задачами, как задать права пользоват...",""],
["./administrators-guide.html","DocumentationEng &#62; Administrator&#39;s Guide","Enter topic text here. How to configure properties of the task with a particular category How to configure relations between categories How to con...",""],
["./administrators-manual.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual","Enter topic text here.",""],
["./admin_guide.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора","Как изменить список состояний у задачи Как разделить пользователей на группы Как разрешить пользователям регистрироваться самостоятельно Как созда...",""],
["./admin_guide_howto_allow_self_registration.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора &#62; Как разрешить пользователям регистрироваться самостоятельно","Если вы хотите, чтобы в вашем проекте участвовали или следили за ним \"внешние\" пользователи, вам понадобится сделать для них правило сам...",""],
["./admin_guide_howto_change_status_list.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора &#62; Как изменить список состояний у задачи","Список состояний задачи определяется ее Процессом. Перейдите в пункт меню Управление задачами » Процессы. Из списка выберите нужный процесс и нажм...",""],
["./admin_guide_howto_create_category.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора &#62; Как создать новую категорию","Перейдите в пункт меню Управление задачами » Категории и на открывшейся странице нажмите кнопку Создать категорию в панели Списка категорий, либо ...",""],
["./admin_guide_howto_create_roles.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора &#62; Как разделить пользователей на группы","Перейдите в меню Управление пользователями » Роли. В появившемся окне нажмите Создать роль, введите ее название и сохраните.",""],
["./admin_guide_howto_filter_tasks.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство администратора &#62; Как фильтровать задачи","Чтобы упорядочивать задачи в списке и отсеивать ненужные, вам и вашим пользователям понадобится набор предустановленных фильтров для задач. Создат...",""],
["./assignee_or_handler.html","Rus &#62; Руководство администратора &#62; Кто такой ответственный, зачем он нужен и что с ним делать?","В английском языке и, соответственно, англоязычных системах управления задачами используется термин \"assignee\", что переводится как &#38;quo...",""],
["./audit_trail.html","Rus &#62; Руководство администратора &#62; Как отследить историю изменения параметров задачи","Что такое аудит изменений и зачем он нужен  В TrackStudio вы можете отслеживать все изменения, которые происходят с задачей и контролировать ...",""],
["./backup_restore.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Резервное копирование и восстановление данных","В этой статье описывается, как выполнить резервное копирование вашего экземпляра TrackStudio, и как восстановить функциональность и данные в случа...",""],
["./basic-definitions-in-trackstud.html","DocumentationEng &#62; User&#39;s Guide &#62; Basic Definitions in TrackStudio","Enter topic text here.",""],
["./bazaar.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM) &#62; Как настроить интеграцию с Bazaar","Для того, чтобы работала интеграция TrackStudio и Bazaar, вам нужно установить специальное дополнение к Bazaar: bzr-xmloutput. Устанавливать его н...",""],
["./before_trigger_check.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как проверить данные перед сохранением задачи (Before Task Edit Trigger)","Чтобы проверять данные перед сохранением существующей задачи, нужно подключить к ее процессу триггер Before Edit Task.",""],
["./bulk_user_change.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как изменить проект по умолчанию для нескольких пользователей","Bulk скрипты в TrackStudio предназначены для выполнения операций над одной или несколькими выбранными из списка задачами. Однако использовать их м...",""],
["./calculated_custom_field.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым","Примеры скриптов вы также можете посмотреть и скачать из репозитория на Github.",""],
["./categories.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач","Что такое категории?      Категории представляют собой типы задач, такие как группа проектов, проект, версия, компонент, сообщение ...",""],
["./categories_copy.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как копировать категорию","Вы можете \"клонировать\" одну или несколько выбранных категорий. При клонировании создаются новые категории, полностью идентичные клониру...",""],
["./categories_deactivate.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как временно отключить неиспользуемые категории","Неиспользуемые категории можно отключить. Отключение категории означает, что нельзя будет создавать новые задачи с этой категорией, но уже созданн...",""],
["./categories_delete.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как удалить неиспользуемую категорию","Вы можете полностью удалить из системы неиспользуемые категории.",""],
["./categories_permissions.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как настроить права для пользователей на задачи с определенной категорией","Вы можете настроить правила, по которым пользователи с определенными ролями смогут или не смогут создавать, редактировать и удалять задачи с опред...",""],
["./categories_ralations.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как настроить связи между категориями","Для того, чтобы использовать созданную категорию, вы должны связать ее с уже существующими категориями. Для этого перейдите через меню \"Управ...",""],
["./categories_templates.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как задать образец для оформления задачи","Иногда требуется, чтобы при создании новой задачи ее описание было выполнено по определенному образцу, содержало определенные пункты и было оформл...",""],
["./categories_triggers.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как привязать триггеры на создание и редактирование задач","Через категории вы можете привязать триггеры, которые будут выполняться при создании или редактировании задачи. Триггеры могут быть трех типов: од...",""],
["./charts.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как построить графики в TrackStudio по вашим данным","Внимание! Данный способ будет работать только в браузерах, поддерживающих HTML5",""],
["./children_list.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Список задач (Task) &#62; Список новых подзадач","Данный простейший скрипт для вычисляемого поля типа задача возвращает список подзадач в начальном состоянии для текущей задачи.",""],
["./chose_test_case.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как указать какой набор тестовых данных использовать для проверки требования","При создании требования укажите набор тестовых данных в соответствующем поле.",""],
["./compile.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как собрать TrackStudio из исходного кода","Для того, чтобы собрать TrackStudio, вам понадобятся: Java SDK и Apache Ant. Лучше, если у вас будет какая-нибудь IDE, но для небольших изменений ...",""],
["./compiling-trackstudio-from-sou.html","DocumentationEng &#62; Developer&#39;s Guide &#62; Compiling TrackStudio from source code","Enter topic text here.",""],
["./configurations.html","Rus &#62; Примеры конфигураций для TrackStudio 4.0","БД TrackStudio для управления проектами по SCRUM БД TrackStudio для управления имуществом. Документация. Конфигурация TrackStudio для IT Service M...",""],
["./configuration_itil.html","Rus &#62; Примеры конфигураций для TrackStudio 4.0 &#62; Конфигурация TrackStudio для IT Service Management / Helpdesk.","TrackStudio Service Desk  Назначение конфигурации  TrackStudio Service Desk - это конфигурация для управления ИТ услугами (IT Service Ma...",""],
["./configuration_scrum.html","Rus &#62; Примеры конфигураций для TrackStudio 4.0 &#62; БД TrackStudio для управления проектами по SCRUM","Scrum в TrackStudio  Данная конфигурация TrackStudio предназначена для организации процесса разработки программного обеспечения по методологи...",""],
["./configuring-ntlm-authenticatio.html","DocumentationEng &#62; Installation Guide &#62; Configuring NTLM Authentication","For authentication of users through NTLM:  Login as Administrator in Microsoft Windows . Run Configure Your Server (Server configuration). ( ...",""],
["./configuring-udf-permissions-fo.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the list of operations with task &#62; Configuring UDF Permissions for custom fields in operations","If for the process, custom fields are given, you can configure the rules, as per which in a particular operation the users will see these custom f...",""],
["./configuring_ssl.html","Rus &#62; Руководство по установке &#62; Установка сертификата SSL","Чтобы установить сертификат SSL для jetty:  Создайте хранилище ключей с помощью утилиты keytool, поставляемой вместе с Sun JDK. Для создания ...",""],
["./connecting-to-a-database.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database","Connecting to HSQL Connecting to PostgreSQL Connecting to MS SQL Server Connecting to Oracle Connecting to DB2 Connecting to Firebird Using a cons...",""],
["./connecting-to-db2.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to DB2","Create user tablespace and temp system tablespace.",""],
["./connecting-to-firebird.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to Firebird","Run the program isql included in Firebird Create the database: SQL&#62; create database &#39;c:\\trackstudio.gdb&#39; user &#39;sysdba&#39; password &#39;masterkey&#39;; SQ...",""],
["./connecting-to-hsql.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to HSQL","Configure the DBMC connection properties: TrackStudio SA: On the tab Database select HSQL from the DBMS list and edit the properties of JDBC conne...",""],
["./connecting-to-ms-sql-server.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to MS SQL Server","Start Enterprise Manager. Create the database. Configure the database connection properties: TrackStudio Standalone: Open the tab Database. Select...",""],
["./connecting-to-oracle.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to Oracle","Create the Tablespace. Create the user for TrackStudio. Set the DBA and Resource permissions for the created user. Configure the DBMC connection p...",""],
["./connecting-to-postgresql.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Connecting to PostgreSQL","Run postmaster. &#62; postmaster -D ../data/ -i -h host.mycompany.com Create the database: &#62; createdb -E UNICODE -U postgres trackstudio Configu...",""],
["./creation-and-initialization-of.html","DocumentationEng &#62; Installation Guide &#62; Creation and initialization of database in PostgreSQL","Run postmaster &#62; postmaster -D ../data/ -i -h host.mycompany.com Create the database: &#62; createdb -E UNICODE -U postgres trackstudio Configur...",""],
["./crowd.html","Rus &#62; Руководство администратора &#62; Как интегрировать TrackStudio с Atlassian Crowd","Atlassian Crowd это веб-приложение для управления учетными записями пользователей в различных приложениях, реализующее технологию единого входа (S...",""],
["./custom_fields.html","Rus &#62; Руководство администратора &#62; Как добавить свои поля в задачи","С помощью дополнительные полей в TrackStudio вы можете хранить специфичную информацию о ваших задачах в структурированном виде. Дополнительные пол...",""],
["./custom_field_date.html","Rus &#62; Руководство администратора &#62; Как добавить свои поля в задачи &#62; Дополнительное поле типа Дата","Свойства  Дата и время, вводимые пользователем.    Ввод  Значение поля представляет собой дату и время и соответствует типу Ca...",""],
["./custom_field_integer.html","Rus &#62; Руководство администратора &#62; Как добавить свои поля в задачи &#62; Дополнительное поле типа Целое","Свойства  Целое число, вводимое пользователем.    Ввод  Целое число должно быть в пределах от –2147483648 до 2147483647. Значе...",""],
["./custom_field_string.html","Rus &#62; Руководство администратора &#62; Как добавить свои поля в задачи &#62; Дополнительное поле типа Строка","Свойства  Одна строка, вводимая пользователем.    Ввод  Строка имеет ограничение по длине в 1800 символов (значение по умолчан...",""],
["./custom_field_text.html","Rus &#62; Руководство администратора &#62; Как добавить свои поля в задачи &#62; Дополнительное поле типа Текст","Свойства  Текст из нескольких строк, вводимый пользователем.    Ввод  Текст не имеет ограничения по длине (значение по умолчан...",""],
["./dashboard_charts.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать свой Dashboard &#62; Как построить графики на Dashboard","Начиная с версии 4.0.15 вы можете использовать макросы для построения графиков и диаграмм в описании задач, операциях и дополнительных полях типа ...",""],
["./database_db2.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под DB2","Создайте user tablespace и temp system tablespace.",""],
["./database_export-import-migration.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Экспорт и импорт базы данных. Миграция","Внимание! Приведенный ниже механизм переноса данных предназначен для переноса только между одинаковыми версиями TrackStudio 4. Для обновления с ве...",""],
["./database_firebird.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под Firebird","Запустите поставляемую с Firebird программу isql  Создайте базу данных:  &#62; create database &#39;c:\\trackstudio.gdb&#39; user &#39;sysdba&#39; passwor...",""],
["./database_hsql.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под HSQL","Настройте свойства соединения с СУБД:  TrackStudio SA: На вкладке База данных выберите из списка СУБД HSQL Russian и отредактируйте свойства ...",""],
["./database_ms-sql-server.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под MS SQL Server","Запустите Enterprise Manager. Создайте базу данных. Настройте свойства соединения с базой:  TrackStudio Standalone:  Откройте вкладку Ба...",""],
["./database_mysql.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под MySQL","Запустите терминальный клиент для MySQL.  shell&#62; mysql -u root  Создайте базу данных:  mysql&#62; create database trackstudio cha...",""],
["./database_oracle.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под ORACLE","Создайте Tablespace. Создайте пользователя для TrackStudio Установите права DBA и Resource созданному пользователю. Обновите JDBC драйвер до вашей...",""],
["./database_postgres.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Создание и инициализация базы данных под PostgreSQL","Запустите postmaster.  &#62; postmaster -D ../data/ -i -h localhost  Создайте базу данных:  &#62; createdb -E UNICODE -h localhost -U...",""],
["./date-(calendar).html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Make the Value of Custom Field Computable &#62; Date (Calendar)","Enter topic text here.",""],
["./date.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Дата (Calendar)","Вычисляем дату и время начала работ по задаче",""],
["./days_since_update.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Целое (Integer) &#62; Число дней, прошедших с обновления задачи","Скрипт возвращает число дней, прошедших с момента последнего обновления незакрытой задачи.",""],
["./dbtool.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных &#62; Использование консольной утилиты для экспорта, импорта и инициализации данных","По многочисленным просьбам в TrackStudio Enterprise 4.0.10 мы добавили консольную утилиту для экспорта и импорта базы данных dbtool. Теперь, даже ...",""],
["./detailed_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Детальный","В детальном отчете для задач выводятся значения всех видимых полей. Фильтр при этом используется лишь для отсеивания ненужных задач. Отчет предста...",""],
["./developers-guide.html","DocumentationEng &#62; Developer&#39;s Guide","How to build project from maven template How to write and debug scripts in IntelliJ IDEA How to use SOAP integration in TrackStudio Compiling Trac...",""],
["./developer_guide.html","Rus &#62; Руководство разработчика","Как писать скрипты и триггеры в TrackStudio Как собрать проект из maven шаблона. Как писать и отлаживать скрипты и триггеры под Eclipse Как писать...",""],
["./distribution_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Распределение","Отчет типа Распределение показывает распределение заданной характеристики задач по одному или двум признакам. Например, количество задач, созданны...",""],
["./documentationeng.html","DocumentationEng","Enter topic text here.",""],
["./dynamic-scheduler.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать настройки операций по расписанию &#62; Как сделать динамический интервал для операций по расписанию","Реализованный механизм находится в проекте скриптов в папке etc/development/scripts. Реализация написана в утилитном классе ItitialJob.",""],
["./emails_for_cc_udf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Множественный список (Multilist) &#62; E-mail адреса пользователей для оповещений через CC","Данный скрипт вычисляет e-mail адреса участников задачи для поля CC, которое используется для оповещения пользователей.",""],
["./extending-and-overriding-the-r.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to Manage Roles of Users &#62; How to define the roles and organize the users into groups &#62; Extending and Overriding the Roles","Extending and Overriding the Roles Navigation: DocumentationEng Administrator&#39;s Guide How to Manage Roles of Users How to define the roles and org...",""],
["./extending_and_overriding_roles.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как определить роли в системе и организовать пользователей в группы &#62; Расширение и переопределение ролей","Иногда требуется, чтобы в одном проекте пользователь был и разработчиком, и тестировщиком - требуется расширить права пользователя. В таком случае...",""],
["./gantt_chart.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Диаграмма Ганта","Вы можете использовать диаграмму Ганта в планировании ваших проектов в качестве иллюстрации графика работ как на этапе планирования, так и на этап...",""],
["./git.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM) &#62; Как настроить интеграцию с Git","Git — распределённая система управления версиями файлов. Проект был создан Линусом Торвальдсом для управления разработкой ядра Linux. Поддержка SC...",""],
["./google_calendar.html","Rus &#62; Руководство администратора &#62; Как интегрировать TrackStudio c Google Calendar","Настройка через TrackStudio Server Manager  Для того, чтобы использовать интеграцию TrackStudio с Google Calendar, вам потребуется учетная за...",""],
["./how-to-allow-independent-regis.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual &#62; How to Allow Independent Registration of Users","Enter topic text here.",""],
["./how-to-assign-triggers-for-cre.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to assign triggers for creating and editing the tasks","Through category, you can assign triggers which will be executed while creating or editing the task. Triggers can be of three types: first types o...",""],
["./how-to-build-project-from-mave.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to build project from maven template","Enter topic text here.",""],
["./how-to-change-the-state-of-tas.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Change the State of Task, Assignee, and Deadlines etc","Enter topic text here.",""],
["./how-to-change-the-states-list-.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual &#62; How to change the States List in a Task","Enter topic text here.",""],
["./how-to-change-trackstudio-url.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to change TrackStudio URL","How to change TrackStudio URL Navigation: DocumentationEng Administrator&#39;s Guide How to change TrackStudio URL ",""],
["./how-to-check-data-before-savin.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to check data before saving the task (Before Task Edit Trigger)","Enter topic text here.",""],
["./how-to-configure-custom-fields.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure custom fields for the workflow","With custom fields, in TrackStudio you can store specific information about your tasks in structural form. Custom fields can be connected to the t...",""],
["./how-to-configure-permissions-f.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the list of operations with task &#62; How to configure permissions for users in operations","You can configure the rules as per which the users with particular roles can or can’t view the operations, execute them and become assignee for th...",""],
["./how-to-configure-properties-of.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to configure properties of the task with a particular category","How to place a button for creating the task on the top bar",""],
["./how-to-configure-relations-bet.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to configure relations between categories","So as to use the category created by you, you must configure its relations with already existing categories. For this purpose, go to the page of c...",""],
["./how-to-configure-states-set-fo.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure states set for the workflow","First of all, what you need to do in the new workflow is to configure the states set. It is better to plan beforehand in which states the task wit...",""],
["./how-to-configure-the-list-of-o.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the list of operations with task","In TrackStudio, tasks are transferred from one state to another with the help of operations. Operations play a very vital role, as this is not onl...",""],
["./how-to-configure-the-set-of-pr.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the set of priorities for a workflow","Priority in a task indicates its importance and defines the sequence of processing of tasks for the users. Priorities set is displayed to the user...",""],
["./how-to-configure-triggers-for-.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the list of operations with task &#62; How to configure triggers for operations","Triggers for operations are a powerful tool for implementing your business-processes.",""],
["./how-to-configure-user-rules-fo.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to configure user rules for tasks with a particular category","You can configure the rules, as per which the users with particular roles can or can’t create, edit and delete the tasks with a particular categor...",""],
["./how-to-copy-a-category.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to Copy a Category","You can &#8220;clone&#8221; one or several of the selected categories. While cloning, new categories are created that are completely identical to the ones bei...",""],
["./how-to-copy-access-control-rul.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to copy access control rules into other project using single button","Enter topic text here.",""],
["./how-to-create-a-new-role.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to Manage Roles of Users &#62; How to create a new role","How to create a new role Navigation: DocumentationEng Administrator&#39;s Guide How to Manage Roles of Users How to create a new role ",""],
["./how-to-create-list-of-requirem.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Create List of Requirements/ Bugs (Errors)/ Test Documentation/ Completions","Enter topic text here.",""],
["./how-to-create-new-category.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual &#62; How to Create New Category","Enter topic text here.",""],
["./how-to-create-new-user.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Create New User","Enter topic text here.",""],
["./how-to-create-project-or-versi.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Create Project or Version","Enter topic text here.",""],
["./how-to-create-requirement.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Create Requirement","Enter topic text here.",""],
["./how-to-define-and-configure-t2.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows","What are the workflows Workflows are the life-cycle of a task. Set of states in which the task is, rules of transition from one state to another, ...",""],
["./how-to-define-and-configure-th.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks?","What is a category? Categories are the types of tasks. Categories are used for anchoring to the tasks of particular workflows, for organizing the ...",""],
["./how-to-define-resolutions-set.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the workflows &#62; How to configure the list of operations with task &#62; How to define resolutions set","Resolutions can be used for indicating the standard reasons for executing the operations. For example, the task can be closed with the resolutions...",""],
["./how-to-define-the-roles-and-or.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to Manage Roles of Users &#62; How to define the roles and organize the users into groups","How to define the roles and organize the users into groups Navigation: DocumentationEng Administrator&#39;s Guide How to Manage Roles of Users How to ...",""],
["./how-to-delete-an-unused-catego.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to delete an unused category","You can permanently delete unused categories from the system.",""],
["./how-to-divide-users-into-group.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual &#62; How to Divide Users into Groups","Enter topic text here.",""],
["./how-to-filter-the-tasks-list.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to Filter the Tasks List","Enter topic text here.",""],
["./how-to-filter-the-tasks.html","DocumentationEng &#62; User&#39;s Guide &#62; Administrator&#39;s Manual &#62; How to Filter the Tasks","Enter topic text here.",""],
["./how-to-import-emails-from-user.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to import emails from users to tasks","Enter topic text here.",""],
["./how-to-import-tasks-from-e-mai.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to import tasks from e-mails sent by unregistered users","How to import tasks from e-mails sent by unregistered users Navigation: DocumentationEng Administrator&#39;s Guide How to import tasks from e-mails se...",""],
["./how-to-indicate-for-testing-wh.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to indicate for testing which Requirement the Test Case is meant","Enter topic text here.",""],
["./how-to-indicate-which-test-cas.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual &#62; How to indicate which Test Case is to be used for Testing the Requirement","Enter topic text here.",""],
["./how-to-make-dynamic-list-of-po.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Make Dynamic List of Possible Values of Custom Field","Enter topic text here.",""],
["./how-to-make-the-value-of-custo.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Make the Value of Custom Field Computable","Enter topic text here.",""],
["./how-to-manage-roles-of-users.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to Manage Roles of Users","How to Manage Roles of Users Navigation: DocumentationEng Administrator&#39;s Guide How to Manage Roles of Users ",""],
["./how-to-perform-actions-on-mult.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to perform actions on multiple tasks","Enter topic text here.",""],
["./how-to-perform-automatic-task-.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Perform Automatic Task Escalation","Enter topic text here.",""],
["./how-to-save-the-history-of-cha.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Save the History of Changes in Task Parameters","Enter topic text here.",""],
["./how-to-set-the-specimen-for-fo.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to set the specimen for formatting of Task","Sometimes while creating a task, you may need that its description is written in a particular format, has some specific points, and is formatted a...",""],
["./how-to-temporarily-disable-unu.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to define and configure the categories of tasks? &#62; How to temporarily disable unused categories","Unused categories can be disabled in TrackStudio. Disabling of a category means that it will no longer be possible to create new tasks with this c...",""],
["./how-to-track-the-history-of-ch.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; How to Track the History of Changes in Task Parameters","How to Track the History of Changes in Task Parameters Navigation: DocumentationEng Administrator&#39;s Guide How to Track the History of Changes in T...",""],
["./how-to-use-rest-api.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to use REST API","Enter topic text here.",""],
["./how-to-use-soap-integration-in.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to use SOAP integration in TrackStudio","Enter topic text here.",""],
["./how-to-write-and-debug-scripts.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to write and debug scripts in IntelliJ IDEA","Enter topic text here.",""],
["./howto_build_maven_project.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как собрать проект из maven шаблона.","Для сборки проекта необходимо иметь установленный maven.",""],
["./howto_change_email_templates.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать свои шаблоны для почтовых уведомлений","В TrackStudio вы можете делать и использовать свои шаблоны для рассылки почтовых уведомлений и подписок. Мы поставляем 2 общих шаблона, текстовый ...",""],
["./howto_change_task.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как изменить состояние задачи, ответственного, сроки выполнения и т.п.","Зайдите в соответствующую задачу. На ее панели выберите кнопку с нужным вам действием. Например Закрыть задачу или Добавить комментарий",""],
["./howto_change_udf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как изменить значение дополнительного поля в задаче","Менять значение дополнительного поля при редактировании задачи достаточно просто: все дополнительные поля содержатся в HashMap внутри SecuredTaskT...",""],
["./howto_create_bug.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как создать список требований/ошибок/тестовой документации/доработок","Списки служат контейнерами (папками) для однородных сущностей в рамках проекта. Создаются списки точно так же, как и любая задача в TrackStudio - ...",""],
["./howto_create_interface.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio","Интерфейсы (templates) используются в TrackStudio для специального доступа к системе. Например, если вы хотите организовать анонимный доступ (без ...",""],
["./howto_create_project.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как создать проект или версию","Перейдите на корневую задачу (пункт \"Проекты\") в дереве задач. Нажмите кнопку Создать проект в верхней панели. В открывшейся форме запол...",""],
["./howto_create_report.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как создать свой отчет в TrackStudio.","В ТС появилась возможность создавать свои отчеты. Рассмотрим пример реализации нового отчета типа список.  В папке /etc/developement/scripts/...",""],
["./howto_create_requirement.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как создать требование","Перейдите к нужному вам списку требований. Нажмите кнопку Создать требование в верхней панели.",""],
["./howto_create_user.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как создать нового пользователя","Эти действия могут выполнять администраторы и менеджеры системы, причем существует иерархия сотрудников – добавлять и удалять разрешено, только по...",""],
["./howto_define_roles_and_groups.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как определить роли в системе и организовать пользователей в группы","Для того, чтобы пользователь с нужной ролью мог что-то делать в определенной задаче, нужно дать ему к этой или вышестоящей задаче доступ. Доступ м...",""],
["./howto_disable_users.html","Rus &#62; Руководство администратора &#62; Как отключить ненужных пользователей","В бесплатной версии TrackStudio есть ограничение на 5 активных пользователей в системе (в Starter Kit - 10 пользователей). Если у вас в системе со...",""],
["./howto_get_public_access.html","Rus &#62; Руководство администратора &#62; Как организовать доступ к TrackStudio без регистрации","В TrackStudio 4.0.8 появилась возможность организации анонимного (публичного) доступа для пользователей без регистрации непосредственно через инте...",""],
["./howto_get_udfvalue.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как получить значения дополнительных полей","Получить значение дополнительного поля, если известен id поля, можно через HashMap",""],
["./howto_hide_blocks.html","Rus &#62; Руководство администратора &#62; Как скрыть ненужные блоки со страницы отображения задачи","В TrackStudio версии 4.0.15 мы к каждому блоку на странице свойств задачи, в котором выводится информация, присвоили индивидуальный ID. Теперь вы ...",""],
["./howto_hide_frame.html","Rus &#62; Руководство администратора &#62; Как скрыть фрейм с деревом задач","Найдите в вашем экземпляре TrackStudio папку webapps/TrackStudio, а в ней файл staticframeset.html",""],
["./howto_import_csv.html","Rus &#62; Руководство администратора &#62; Как импортировать в TrackStudio ваши данные","Есть много способов перенести ваши данные в TrackStudio. Самый простой из них - импортировать их в формате CSV. Как правило, в развитых системах у...",""],
["./howto_import_email.html","Rus &#62; Руководство администратора &#62; Как импортировать письма от пользователей в задачи","Вы можете автоматически импортировать письма от ваших пользователей в систему TrackStudio в виде новых задач, либо комментариев к существующим.",""],
["./howto_make_own_dashboard.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать свой Dashboard","Начиная с версии 4.0.7 в TrackStudio есть возможность делать dashboard для проектов и задач. По сути, Dashboard - это представление задачи в виде ...",""],
["./howto_make_reports.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio","В TrackStudio отчеты предназначены для представления данных. Все отчеты используют фильтры для выборки нужных задач. Всего существует 7 типов отче...",""],
["./howto_manage_password_settings.html","Rus &#62; Руководство администратора &#62; Как управлять настройками безопасности","Как правило, мы поставляем примеры настроенных конфигураций, в которых корневой пользователь имеет логин root и пароль root, а у остальных пользов...",""],
["./howto_notify_unregistered_users.html","Rus &#62; Руководство администратора &#62; Как оповещать об изменениях по e-mail незарегистрированных пользователей","В TrackStudio есть возможность оповещения незарегистрированных в системе пользователей через СС.",""],
["./howto_notify_users.html","Rus &#62; Руководство администратора &#62; Как оповещать пользователей об изменениях по e-mail","Пользователи в TrackStudio могут получать оповещения по почте о новых задачах или об изменении существующих, а также получать периодические уведом...",""],
["./howto_specify_requirement.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как указать, для проверки какого требования предназначен набор тестовых данных","При создании набора тестовых данных укажите требование в соответствующем поле.",""],
["./howto_use_lookup.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать подстановочные (Lookup) скрипты","TrackStudio позволяет использовать список готовых значений для заполнения пользовательских полей.",""],
["./howto_use_webdav.html","Rus &#62; Руководство администратора &#62; Как редактировать приложенные файлы через WebDav.","В TrackStudio есть возможность редактировать приложенные файлы через WebDav.",""],
["./how_to_filter_tasks.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя &#62; Как отфильтровать список задач","Списки задач в TrackStudio выводятся с учетом параметров, заданных в Фильтрах. Для того, чтобы сменить фильтр, просто нажмите его кнопку на панели...",""],
["./import_from_unregistered.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как импортировать задачи из email от незарегистрированых пользователей","Предварительно вам следует настроить импорт задач от существующих пользователей.",""],
["./initializing_database.html","Rus &#62; Руководство по установке &#62; Создание и настройка базы данных","Создание и инициализация базы данных под PostgreSQL",""],
["./installation-guide.html","DocumentationEng &#62; Installation Guide","Updating TrackStudio Upgrade from version 4.0.x to 5.0.x Upgrading the minor versions (4.0.x) Upgrade from version 3.5 Installing on Windows Insta...",""],
["./installation_guide.html","Rus &#62; Руководство по установке","Обновление TrackStudio Обновление минорных версий (5.0.x) Обновление c версии 4.0.x до 5.0.x Обновление минорных версий (4.0.x) Обновление c верси...",""],
["./installing-on-linux.html","DocumentationEng &#62; Installation Guide &#62; Installing on Linux","We are releasing TrackStudio Enterprise in two versions: Standalone - for servers with graphical user interface X-Windows and WAR - for servers wi...",""],
["./installing-on-windows.html","DocumentationEng &#62; Installation Guide &#62; Installing on Windows","We are releasing TrackStudio Enterprise in two versions: Standalone - for servers with graphical user interface and WAR - for servers without a gr...",""],
["./installing-ssl-certificate.html","DocumentationEng &#62; Installation Guide &#62; Installing SSL Certificate","For configuring SSL certificate for jetty: Create keystore with the help of utility keytool, included in Sun JDK. For creating the certificate, yo...",""],
["./installing-trackstudio-standa2.html","DocumentationEng &#62; Installation Guide &#62; Installing on Linux &#62; Installing TrackStudio Standalone in Linux","Important! Beginning with version TrackStudio 4.0.10, the system is shipped with uninitialized database. Here is the description, how to initializ...",""],
["./installing-trackstudio-standal.html","DocumentationEng &#62; Installation Guide &#62; Installing on Windows &#62; Installing TrackStudio Standalone in Windows","Important! Beginning version TrackStudio 4.0.10, the system is shipped with uninitialized database. Here is the description about how to initializ...",""],
["./installing-trackstudio-war-in-.html","DocumentationEng &#62; Installation Guide &#62; Installing on Windows &#62; Installing TrackStudio War in Windows","Note. Beginning TrackStudio 4.0.10, the system comes with uninitialized database. The method for initializing it has been described here.",""],
["./installing-trackstudio-war-in2.html","DocumentationEng &#62; Installation Guide &#62; Installing on Linux &#62; Installing TrackStudio WAR in Linux","Note. Beginning version TrackStudio 4.0.10, the system comes with uninitialized database. The method for initializing the database has been descri...",""],
["./integer.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Make the Value of Custom Field Computable &#62; Integer","Enter topic text here.",""],
["./integerudf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Целое (Integer)","Число дней, прошедших с обновления задачи",""],
["./interface_audit.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio &#62; Как вывести историю операций с задачей","Список сообщений можно получить так:  &#60;#assign msgs = task.messages/&#62; &#60;#if msgs?exists &#38;&#38; (msgs?size&#62;0)&#62; &#60;#list msg...",""],
["./interface_create_task.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio &#62; Как создать новую задачу","Для того, чтобы дать пользователям возможность создавать задачи из вашего интерфейса, вставьте на странице форму:",""],
["./interface_links.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio &#62; Как организовать переход по ссылкам внутри шаблона","Ссылка в шаблонах строятся по формату:  ${contextPath}/template/${template}/task/${task.number}  Где ${contextPath} - контекст (переменн...",""],
["./interface_operation.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio &#62; Как добавить комментарий","Чтобы добавить в интерфейс возможность для пользователей оставлять комментарии к задаче, добавьте на страницу следующую форму:",""],
["./interface_task.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как быстро и просто сделать свой интерфейс для TrackStudio &#62; Как вывести на страницу текущую задачу","Текущая задача хранится в переменной task. Вы можете выводить в шаблоне значения полей задачи, например таких:",""],
["./jconsole.html","Rus &#62; Руководство администратора &#62; Мониторинг работы TrackStudio с помощью jconsole","В Java встроено расширение для управления (JMX), через которое с помощью графической утилиты jconsole вы можете посмотреть, как ведет себя TrackSt...",""],
["./jes.html","Rus &#62; Руководство администратора &#62; Как настроить почтовый сервер JES","Для того, чтобы использовать систему уведомлений и возможность импортировать письма электронной почты как задачи, TrackStudio нужен POP3/SMTP серв...",""],
["./josso.html","Rus &#62; Руководство администратора &#62; Как интегрировать TrackStudio c JOSSO","JOSSO, или Java Open Single Sign-On, это решение с открытым исходным кодом на J2EE для централизованной авторизации и аутентификации пользователей...",""],
["./ldap_linux.html","Rus &#62; Руководство по установке &#62; Установка OpenLDAP и настройка авторизации пользователей TrackStudio","Установите OpenLDAP из репозиториев  sudo apt-get install slapd ldap-utils      При установке вам будет предложено ввести паро...",""],
["./ldap_windows.html","Rus &#62; Руководство по установке &#62; Настройка авторизации пользователей через MS Active Directory","Настройка входа через Microsoft Active Directory Service",""],
["./linkudf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Ссылка (URL)","Список задач пользователя в проекте.",""],
["./linux_setup.html","Rus &#62; Руководство по установке &#62; Установка под Linux","Мы выпускаем TrackStudio Enterprise в двух вариантах: Standalone — для компьютеров с графической оболочкой X-Windows и WAR — для серверов без граф...",""],
["./linux_setup_console.html","Rus &#62; Руководство по установке &#62; Установка под Linux &#62; Установка TrackStudio Standalone из консоли","Для работы с TrackStudio на вашем сервере должны быть установлены библиотеки X11, т.к. они требуются Java для работы с графическими файлами. При э...",""],
["./linux_setup_sa.html","Rus &#62; Руководство по установке &#62; Установка под Linux &#62; Установка TrackStudio Standalone","Для того, чтобы настроить и запустить TrackStudio Standalone на сервере с графической оболочкой:",""],
["./linux_setup_war.html","Rus &#62; Руководство по установке &#62; Установка под Linux &#62; Установка TrackStudio WAR","Внимание! Начиная с версии TrackStudio 4.0.10 система поставляется с неинициализированной базой данных. Как ее инициализировать, описано ниже.",""],
["./linux_x-window.html","Rus &#62; Руководство по установке &#62; Установка под Linux &#62; Настройка X Window","TrackStudio не содержат графические библиотеки для создания цветов, шрифтов и другой графической информации. Java использует системные библиотеки ...",""],
["./list-of-similar-tasks.html","DocumentationEng &#62; Developer&#39;s Guide &#62; List of Similar Tasks","Enter topic text here.",""],
["./list_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Список","Отчет представляет собой список задач (и, при определенных настройках, операций с задачами) в виде таблицы. Перечень выводимых в отчет полей опред...",""],
["./localize.html","Rus &#62; Руководство администратора &#62; Как локализовать интерфейс TrackStudio","В этой статье описывается, как самостоятельно локализовать интерфейс TrackStudio",""],
["./manage_categories.html","Rus &#62; Руководство администратора &#62; Как определить и настроить категории задач &#62; Как настроить свойства задач с определенной категорией","Как поместить кнопку создания задачи на верхнюю панель",""],
["./memoudf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Текст (Text)","Время, затраченное пользователями на задачу",""],
["./mercurial.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM) &#62; Как настроить интеграцию с Mercurial","Mercurial — кроссплатформенная распределённая система управления версиями, разработанная для эффективной работы с очень большими репозиториями код...",""],
["./multilist.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Множественный список (Multilist)","E-mail адреса пользователей для оповещений через CC",""],
["./notification_trigger.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как уведомить нескольких пользователей о задаче","Данный набор триггеров предназначен для того, чтобы пользователи при редактировании задачи и выполнении над ней операций могли прямо указать, кого...",""],
["./ntlm_auth.html","Rus &#62; Руководство по установке &#62; Настройка авторизации через NTLM","Чтобы настроить авторизацию пользователей через NTLM:",""],
["./number-of-days-since-task-upda.html","DocumentationEng &#62; Developer&#39;s Guide &#62; How to Make the Value of Custom Field Computable &#62; Integer &#62; Number of days since task update","Enter topic text here.",""],
["./participants_list.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Список Пользователей &#62; Список участников для задачи","Данный скрипт вычисляет значение дополнительного поля типа User и выводит список пользователей, оставивших к задаче комментарии (или выполнивших л...",""],
["./perforce.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM) &#62; Как настроить интеграцию с Perforce","Установка и настройка сервера Perforce  Perforce - это коммерческая система управления версиями, созданная компанией Perforce Software. Один ...",""],
["./process_note_operations.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как выполнить действия над несколькими задачами","Выполнить действия над несколькими выбранными задачами можно с помощью Bulk-скриптов. В отличие от триггеров, bulk-скрипты выполняются не автомати...",""],
["./project-overview.html","DocumentationEng &#62; User&#39;s Guide &#62; Project Overview","Enter topic text here.",""],
["./requirements-management-overview.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\"","Управление требованиями – это одна из самых важных составных частей процесса разработки. Без сформулированных требований, как правило, практически...",""],
["./requirements_managment_config_overview.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Обзор проекта","В проекте созданы несколько пользователей, выполняющих различные роли, подробная информация о них представлена в таблице.",""],
["./requirements_managment_definitions.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Основные понятия TrackStudio","Одной из главных особенностей TrackStudio является иерархическая организация, как задач, так и пользователей. Причем, настройки (процессы, категор...",""],
["./rest_api.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать REST API","В настоящее время TrackStudio REST API находится в экспериментальной фазе. Мы планируем развивать этот интерфейс, поэтому структура запросов и воз...",""],
["./roles.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей","В TrackStudio нет групп пользователей в общепринятом значении этого термина. Обычно управление группами в системах управления инцидентами сводится...",""],
["./roles_actions.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как разрешить или запретить пользователю выполнять определенные действия","Вы можете ограничить для пользователей с определенными ролями доступ в некоторые разделы TrackStudio. Например, разумно будет запретить пользовате...",""],
["./roles_categories_actions.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Настройка прав на задачи с определенной категорией","В главе об управлении категориями задач мы уже описывали, как настроить права пользователей для определенной категории. При настройке новой или уж...",""],
["./roles_create.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как создать новую роль","Для регистрации новой роли пользователей в системе:",""],
["./roles_processes.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как настроить права для пользователей на операции и дополнительные поля в процессах","Вы можете настроить права пользователей с определенной ролью на процессы (выполнение операций для этих процессов) и для дополнительных полей.",""],
["./roles_rules_user_filds.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как запретить просмотр или редактирование полей пользователей","В TrackStudio вы можете управлять видимостью и доступностью для редактирования полей пользователей для каждой роли отдельно. Для того, чтобы настр...",""],
["./roles_task_fields.html","Rus &#62; Руководство администратора &#62; Как управлять ролями пользователей &#62; Как запретить просмотр или редактирование полей в задачах","В TrackStudio вы можете гибко управлять видимостью и доступностью для редактирования полей в задачах для каждой роли отдельно. Для того, чтобы нас...",""],
["./rus.html","Rus","Enter topic text here.",""],
["./scheduler.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать настройки операций по расписанию","В системе введен новый тип скриптов. Они используются для работы с автоматическими задачами : рассылка, импорт, синхронизация с репозиториями (ста...",""],
["./scm.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM)","TrackStudio поддерживает интеграцию с несколькими системами контроля версий, такими как Subversion, CVS, Bazaar, Perforce, Git и Mercurial. Вы мож...",""],
["./scripts_deadline_by_priority.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как установить Deadline создаваемой задачи в зависимости от приоритета","Этот Create Task/Before триггер устанавливает поле \"Сделать до\" в зависимости от назначенного приоритета. В этом примере не учитываются ...",""],
["./scripts_debug_eclipse.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как писать и отлаживать скрипты и триггеры под Eclipse","Дополнительную функциональность в TrackStudio можно реализовать с помощью скриптов и триггеров. Скрипты обычно соответствуют вычисляемым дополните...",""],
["./scripts_debug_idea.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как писать и отлаживать скрипты и триггеры под IntelliJ IDEA","Дополнительную функциональность в TrackStudio можно реализовать с помощью скриптов и триггеров. Скрипты обычно соответствуют вычисляемым дополните...",""],
["./scripts_howto.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio","Как собрать проект из maven шаблона. Как писать и отлаживать скрипты и триггеры под Eclipse Как писать и отлаживать скрипты и триггеры под Intelli...",""],
["./script_coping_access_rules.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Копируем права доступа в другой проект одной кнопкой","Одна из самых популярных конфигураций TrackStudio: много однотипных проектов, права на которые задаются для разных команд по-разному. Эта конфигур...",""],
["./script_sprinlist.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать подстановочные (Lookup) скрипты &#62; Как сделать динамический список возможных значений дополнительного поля","Для того, чтобы сделать возможным выбор значений дополнительного поля из выпадающего списка, вам потребуется создать само поле типа \"Строка&#38;q...",""],
["./security-settings.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; Security Settings","Security Settings Navigation: DocumentationEng Administrator&#39;s Guide Security Settings ",""],
["./similar_tasks.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Список задач (Task) &#62; Список похожих задач","Скрипт возвращает список похожих задач. Будет полезен при общении с пользователями через TrackStudio.",""],
["./soap.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как использовать интерфейс SOAP для TrackStudio","Для работы с SOAP в папке etc/deveopment/soap лежит проект.",""],
["./starting-trackstudio-as-a-wind.html","DocumentationEng &#62; Installation Guide &#62; Installing on Windows &#62; Starting TrackStudio as a Windows service","Jetty (applications server, supplied with the TrackStudio SA)",""],
["./starting_windows_service.html","Rus &#62; Руководство по установке &#62; Установка под Windows &#62; Запуск TrackStudio как сервиса Windows","Jetty (сервер приложений, поставляемый с TrackStudio SA)",""],
["./start_date.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Дата (Calendar) &#62; Вычисляем дату и время начала работ по задаче","package scripts.task_custom_field_value;  import com.trackstudio.exception.GranException; import com.trackstudio.external.TaskUDFValueScript;...",""],
["./subscriptions_schedule.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Альтернативная реализация механизма рассылки","Сделать отчет о состоянии задач для пользователя позволяет стандартный механизм \"Подписки на уведомления\".",""],
["./svn.html","Rus &#62; Руководство администратора &#62; Как настроить интеграцию с системами управления исходным кодом (SCM) &#62; Как настроить интеграцию с SVN","TrackStudio поддерживает интеграцию с несколькими системами контроля версий, такими как Subversion, CVS, Bazaar и Perforce. Вы можете использовать...",""],
["./tasks_list_for_user.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Ссылка (URL) &#62; Список задач пользователя в проекте.","Скрипт возвращает ссылку, отфильтрованных по фильтру \"Мои задачи\", задач текущего пользователя.",""],
["./taskudf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Список задач (Task)","Список новых подзадач Список похожих задач",""],
["./task_escalation.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать автоматическую эскалацию задачи","В общем смысле эскалация задачи - это перевод ее в другое состояние, другому исполнителю или повышение ее приоритета в зависимости от условий. Нап...",""],
["./time-tracking-in-trackstudio.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; Time Tracking in TrackStudio","Time Tracking in TrackStudio Navigation: DocumentationEng Administrator&#39;s Guide Time Tracking in TrackStudio ",""],
["./timesheet_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Табель","В табеле выводится количество часов, потраченных пользователем, на выполнение задач за указанный период. Фильтр при этом используется лишь для отс...",""],
["./time_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Отчет о затраченном времени","В отчете о затраченном времени вы можете увидеть активность пользователей по задачам, выраженную в часах. Этот отчет будет вам полезен, если вы ис...",""],
["./time_spent_for_task.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Текст (Text) &#62; Время, затраченное пользователями на задачу.","Скрипт используется в поле типа текст с включенной опцией HTML-вид. Скрипт возвращает таблицу с временем, которое потратил на задачу каждый пользо...",""],
["./time_tracking.html","Rus &#62; Руководство администратора &#62; Как с помощью TrackStudio учитывать рабочее время","С помощью TrackStudio вы можете учитывать свое рабочее время, затраченное на решение задач, и рабочее время своих сотрудников.",""],
["./trackstudio_url.html","Rus &#62; Руководство по установке &#62; Как сменить URL TrackStudio","По-умолчанию TrackStudio открывается по адресу http://localhost:8888/TrackStudio.",""],
["./tree_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Отчет о структуре задач","С помощью отчета о структуре задач вы можете экспортировать данные в MS Project, либо в другую систему, поддерживающую формат XML, либо с помощью ...",""],
["./trend_report.html","Rus &#62; Руководство администратора &#62; Как построить отчеты в TrackStudio &#62; Тренд","Отчет типа Тренд позволяет оценить количество новых, открытых, закрытых задач в каждый отчетный период. В отчете подсчитывается количество операци...",""],
["./update_5_0_x.html","Rus &#62; Руководство по установке &#62; Обновление TrackStudio &#62; Обновление минорных версий (5.0.x)","Если у Вас вариант TrackStudio WAR:  Скачайте самую свежую версию TrackStudio WAR. Замените trackstudio.war новой версией. Перезапустите Trac...",""],
["./update_minor_4_0_x.html","Rus &#62; Руководство по установке &#62; Обновление TrackStudio &#62; Обновление минорных версий (4.0.x)","Если у Вас вариант TrackStudio WAR:  Скачайте самую свежую версию TrackStudio WAR. Замените trackstudio.war новой версией. Перезапустите Trac...",""],
["./update_to_4_0_x.html","Rus &#62; Руководство по установке &#62; Обновление TrackStudio &#62; Обновление c версии 3.5.x до 4.0.x","Если у Вас вариант TrackStudio Standalone:  Скачайте самый свежий дистрибутив TrackStudio 4.0 Standalone Остановите ваш экземпляр TrackStudio...",""],
["./update_to_5_0_x.html","Rus &#62; Руководство по установке &#62; Обновление TrackStudio &#62; Обновление c версии 4.0.x до 5.0.x","Если у Вас вариант TrackStudio WAR:  Скачайте самую свежую версию TrackStudio WAR. Замените trackstudio.war новой версией. Перезапустите Trac...",""],
["./update_trackstudio.html","Rus &#62; Руководство по установке &#62; Обновление TrackStudio","Обновление минорных версий (5.0.x) Обновление c версии 4.0.x до 5.0.x Обновление минорных версий (4.0.x) Обновление c версии 3.5.x до 4.0.x",""],
["./updating-trackstudio.html","DocumentationEng &#62; Installation Guide &#62; Updating TrackStudio","Upgrade from version 4.0.x to 5.0.x Upgrading the minor versions (4.0.x) Upgrade from version 3.5",""],
["./upgrade-from-version-3_5.html","DocumentationEng &#62; Installation Guide &#62; Updating TrackStudio &#62; Upgrade from version 3.5","For TrackStudio Standalone: Download the latest TrackStudio Standalone Stop TrackStudio Install downloaded TrackStudio Standalone in separate dire...",""],
["./upgrade-from-version-4_0_x-to-.html","DocumentationEng &#62; Installation Guide &#62; Updating TrackStudio &#62; Upgrade from version 4.0.x to 5.0.x","If you possess the version TrackStudio WAR: Download the latest version of TrackStudio WAR. Replace trackstudio.war by the new version. Restart Tr...",""],
["./upgrading-the-minor-versions-(.html","DocumentationEng &#62; Installation Guide &#62; Updating TrackStudio &#62; Upgrading the minor versions (4.0.x)","If you possess the version TrackStudio WAR: Download the latest version of TrackStudio WAR. Replace trackstudio.war by the new version. Restart Tr...",""],
["./user-manual.html","DocumentationEng &#62; User&#39;s Guide &#62; User Manual","Enter topic text here.",""],
["./users-guide.html","DocumentationEng &#62; User&#39;s Guide","Project Overview Basic Definitions in TrackStudio Administrator&#39;s Manual How to Allow Independent Registration of Users How to Create New Category...",""],
["./users_guide.html","Rus &#62; Руководство пользователя &#62; Пример конфигурации \"Управление требованиями\" &#62; Руководство пользователя","Как изменить состояние задачи, ответственного, сроки выполнения и т.п.",""],
["./userudf.html","Rus &#62; Руководство разработчика &#62; Как писать скрипты и триггеры в TrackStudio &#62; Как сделать значение дополнительного поля вычисляемым &#62; Список Пользователей","Список участников для задачи",""],
["./user_guide.html","Rus &#62; Руководство пользователя","Пример конфигурации \"Управление требованиями\" Обзор проекта Основные понятия TrackStudio Руководство администратора Как изменить список ...",""],
["./user_logon_restriction.html","Rus &#62; Руководство администратора &#62; Как запретить вход в систему определенным группам пользователей","Часто клиенты спрашивают, как ограничить внешним пользователям доступ в систему так, чтобы почтовые уведомления они получали, но в саму систему че...",""],
["./using-a-console-app-dbtool-for.html","DocumentationEng &#62; Installation Guide &#62; Connecting to a Database &#62; Using a console app dbtool for exporting and importing a database","In TrackStudio Enterprise 4.0.10 we added a console app dbtool export and import database. Now you can get an anonymized backup file without windo...",""],
["./who-is-assignee-and-why-is-he-.html","DocumentationEng &#62; Administrator&#39;s Guide &#62; Who is assignee and why is he required?","In TrackStudio, &#8220;Assignee&#8221; is the person who is not just given a task for execution but he is the person, who is responsible for that particular t...",""],
["./windows_setup.html","Rus &#62; Руководство по установке &#62; Установка под Windows","Мы настоятельно рекомендуем скачивать и устанавливать TrackStudio Enterprise Standalone, используйте WAR версию только в исключительных случаях, т...",""],
["./windows_setup_sa.html","Rus &#62; Руководство по установке &#62; Установка под Windows &#62; Установка TrackStudio Standalone под Windows","Для того, чтобы установить TrackStudio Standalone:",""],
["./windows_setup_war.html","Rus &#62; Руководство по установке &#62; Установка под Windows &#62; Установка WAR-версии TrackStudio под Windows","Чтобы установить и настроить TrackStudio WAR в Windows:",""],
["./workflow.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы","Что такое процессы?  Процессы представляют собой жизненный цикл задачи. В процессах описывается набор состояний, в которых может находиться з...",""],
["./workflow_operations.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей","В TrackStudio задачи переводятся из одного состояния в другое с помощью операций. Операции играют чрезвычайно важную роль, т.к. это не только един...",""],
["./workflow_operation_permissions.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей &#62; Как настроить разрешения для пользователей в операциях","Вы можете настроить правила, по которым пользователи с определенными ролями смогут или не смогут видеть операции, выполнять их и становиться ответ...",""],
["./workflow_operation_resolutions.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей &#62; Как задать набор резолюций","Резолюции можно использовать для указания стандартизованных причин выполнения операции. Например, задача может быть закрыта с резолюциями \"ис...",""],
["./workflow_operation_transitions.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей &#62; Как настроить переходы из одного состояния в другое","Для того, чтобы выполнение операции приводило к переводу задачи из одного состояния в другое, нужно для этой операции задать переходы.",""],
["./workflow_operation_triggers.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей &#62; Как настроить триггеры для операций","Триггеры для операций — очень мощный инструмент для реализации ваших бизнес-процессов.",""],
["./workflow_operation_udf_permissions.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить список операций с задачей &#62; Как настроить разрешения для дополнительных полей в операциях","Если для процесса заданы дополнительные поля, вы можете настроить правила, по которым в определенной операции пользователи будут видеть эти дополн...",""],
["./workflow_priorities.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить набор приоритетов для процесса","Приоритет в задаче указывает на ее важность и определяет порядок обработки задач для пользователей. Набор приоритетов выводится пользователю в вид...",""],
["./workflow_states.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить набор состояний для процесса","Первое, что вы должны сделать в новом процессе — это настроить набор состояний. Лучше заранее продумать, в каких состояниях может находиться задач...",""],
["./workflow_udf.html","Rus &#62; Руководство администратора &#62; Как определить и настроить процессы &#62; Как настроить дополнительные поля для процесса","С помощью дополнительные полей в TrackStudio вы можете хранить специфичную информацию о ваших задачах в структурированном виде. Дополнительные пол...",""],
["./xmpp.html","Rus &#62; Руководство администратора &#62; Как настроить уведомления через Jabber/XMPP","В TrackStudio есть возможность посылать уведомления о событиях по протоколу XMPP вместе с или вместо уведомлений по электронной почте.",""],
["./x_509_cert.html","Rus &#62; Руководство по установке &#62; Настройка авторизации по X.509","TrackStudio поддерживает вход в систему с использованием клиентских сертификатов (X.509).",""],
["./yourkit.html","Rus &#62; Руководство администратора &#62; Как оценить быстродействие и использование памяти с помощью YourKit","YourKit — коммерческая утилита для оценки и оптимизации быстродействия программ, написанных на Java. Если вам кажется, что TrackStudio работает не...",""]];
